#!/usr/local/bin/perl

# run_cla_c50rules
# by Johann Petrak (OeFAI)

$pgmversion = '$Revision: 3.0.2.1 $';
$pgmdate    = '$Date: 2002/08/24 07:22:42 $';
$rcsid      = '$Id: run_cla_c50rules,v 3.0.2.1 2002/08/24 07:22:42 johann Exp $';
$dummy      = '$';   # just here to satisfy the dumb emacs fontifyer

use vars qw($pgmname $pgmpath $trainargs $args
	    $testargs $predfile $filestem);
use Getopt::Long;
use File::Basename;
$pgmname = $0;
$pgmpath = dirname($pgmname);
push(@INC,$pgmpath);
require run_lib;
require config;

beginLA("c50rules",$pgmversion); 

# ARGGGGGHHH: we need to temporarily rename the test file to
# prevent c5.0 from running the testing step automatically
rename "$filestem.test", "$filestem.tmptest" ||
  exitErr("Problem renaming $filestem.test to $filestem.tmptest: $!\n");

startCMD("c5.0 -r -f $filestem $args $trainargs");
# Skip everything until "Evaluation on" 
while (defined($_=getLine())) {
  if (/^Evaluation on /) {
    last;
  }
}
while (defined($_=getLine())) {
  if (/^\s+Size/) {
    $_ = <IN>; $_ = <IN>;
    /^\s+(\d+)\s+\d+\(([^%]+)%\)/;
    $k{"Size"} = $1;
    $k{"Resubsterror"} = $2 / 100;
    last;  # this is really not necessary if we dont have a .test file
  }
}
while (defined($_=getLine())) {}
$k{"Traintime"} = stopCMD();

# rename back to original name
rename "$filestem.tmptest", "$filestem.test" ||
  exitErr("Problem renaming $filestem.tmptest to $filestem.test: $!\n");

startCMD("c5test -r -f $filestem -p $predfile $args $testargs");
while (defined($_=getLine())) {
  if (/^Error rate:\s+([0-9\.]+)/) {
    $k{"Error"} = $1;
  }
}
$k{"Testtime"} = stopCMD();

rmFile("$filestem.tmp");
rmFile("$filestem.tree");
rmFile("$filestem.rules");

endLA();
