#!/usr/local/bin/perl

# run_cpa_fselC50T
# by Johann Petrak (OeFAI)

$pgmversion = '$Revision: 3.0.2.1 $';
$pgmdate    = '$Date: 2002/08/24 07:22:42 $';
$rcsid      = '$Id: run_cpa_fselC50T,v 3.0.2.1 2002/08/24 07:22:42 johann Exp $';
$dummy      = '$';   # just here to satisfy the dumb emacs fontifyer

# CHANGES:
# 2001-10-16 2.1: add support for config.pm

use vars qw($pgmname $pgmpath $args $trainargs $debug %k
	    $time $filestem $la);
use Getopt::Long;
use File::Basename;
$pgmname = $0;
$pgmpath = dirname($pgmname);
push(@INC,$pgmpath);
require run_lib;
require config;

beginPA("fselC50T",$pgmversion); 
$debug = 1; # we always want verbose mode here 

# avoid the C5.0 from doing the testing step
rename "$filestem.test", "$filestem.tmptest" ||
  exitErr("Problem renaming $filestem.test to $filestem.tmptest: $!\n");
startCMD("c5.0 -f $opt_istem");
while (defined($_=getLine())) {
}
# rename back to original name
rename "$filestem.tmptest", "$filestem.test" ||
  exitErr("Problem renaming $filestem.tmptest to $filestem.test: $!\n");


addCMD("atrib_list -f $opt_istem");
while (defined($_=getLine())) {
  if (/,/) {
    $attrs = $_;
  }
}
print "Selecting attributes: $attrs\n";

addCMD("perl $pgmpath/project $opt_istem $opt_ostem $attrs");
while (defined($_=getLine())) {
}


$k{"PAtime_fselC50T"} = stopCMD();

endPA();
